language: node_js
node_js:
  - "node"
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  only:
    - master
    - next
cache:
  directories:
    - "$HOME/.npm"
notifications:
  email: false
